CREATE TABLE IF NOT EXISTS users (
  id INT PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(50) UNIQUE NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  name VARCHAR(100),
  role VARCHAR(20) DEFAULT 'user',
  avatar_url VARCHAR(500),
  phone VARCHAR(20),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  last_login TIMESTAMP NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS settings (
  id INT PRIMARY KEY AUTO_INCREMENT,
  setting_key VARCHAR(100) UNIQUE NOT NULL,
  setting_value TEXT,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS contacts (
  id INT PRIMARY KEY AUTO_INCREMENT,
  user_id INT NOT NULL,
  first_name VARCHAR(50) NOT NULL,
  last_name VARCHAR(50),
  email VARCHAR(255),
  phone VARCHAR(20),
  company VARCHAR(100),
  status VARCHAR(20) DEFAULT 'lead',
  tags TEXT,
  notes TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS ai_tools (
  id INT PRIMARY KEY AUTO_INCREMENT,
  user_id INT NOT NULL,
  tool_name VARCHAR(100) NOT NULL,
  category VARCHAR(50),
  description TEXT,
  url VARCHAR(500),
  daily_usage INT DEFAULT 0,
  weekly_usage INT DEFAULT 0,
  monthly_usage INT DEFAULT 0,
  rating INT DEFAULT 0,
  notes TEXT,
  is_favorite BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS productivity_sessions (
  id INT PRIMARY KEY AUTO_INCREMENT,
  user_id INT NOT NULL,
  session_name VARCHAR(100) NOT NULL,
  ai_tools_used TEXT,
  duration_minutes INT DEFAULT 0,
  productivity_score INT DEFAULT 0,
  notes TEXT,
  session_date DATE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS achievements (
  id INT PRIMARY KEY AUTO_INCREMENT,
  user_id INT NOT NULL,
  achievement_type VARCHAR(50) NOT NULL,
  achievement_name VARCHAR(100) NOT NULL,
  description TEXT,
  points INT DEFAULT 0,
  unlocked_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Ensure all columns exist (CREATE TABLE IF NOT EXISTS doesn't update existing tables)
-- Columns referenced in code but missing from CREATE TABLE:
ALTER TABLE `users` ADD COLUMN IF NOT EXISTS `columns` VARCHAR(255) DEFAULT NULL;
ALTER TABLE `users` ADD COLUMN IF NOT EXISTS `placeholders` VARCHAR(255) DEFAULT NULL;
ALTER TABLE `contacts` ADD COLUMN IF NOT EXISTS `points` VARCHAR(255) DEFAULT NULL;
ALTER TABLE `ai_tools` ADD COLUMN IF NOT EXISTS `points` VARCHAR(255) DEFAULT NULL;
ALTER TABLE `productivity_sessions` ADD COLUMN IF NOT EXISTS `points` VARCHAR(255) DEFAULT NULL;
-- All schema columns (ensures existing tables get new columns on rebuild):
ALTER TABLE `users` ADD COLUMN IF NOT EXISTS `username` VARCHAR(50) UNIQUE NOT NULL;
ALTER TABLE `users` ADD COLUMN IF NOT EXISTS `email` VARCHAR(255) UNIQUE NOT NULL;
ALTER TABLE `users` ADD COLUMN IF NOT EXISTS `password_hash` VARCHAR(255) NOT NULL;
ALTER TABLE `users` ADD COLUMN IF NOT EXISTS `name` VARCHAR(100);
ALTER TABLE `users` ADD COLUMN IF NOT EXISTS `role` VARCHAR(20) DEFAULT 'user';
ALTER TABLE `users` ADD COLUMN IF NOT EXISTS `avatar_url` VARCHAR(500);
ALTER TABLE `users` ADD COLUMN IF NOT EXISTS `phone` VARCHAR(20);
ALTER TABLE `users` ADD COLUMN IF NOT EXISTS `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `users` ADD COLUMN IF NOT EXISTS `last_login` TIMESTAMP NULL;
ALTER TABLE `users` ADD COLUMN IF NOT EXISTS `columns` VARCHAR(255) DEFAULT NULL;
ALTER TABLE `users` ADD COLUMN IF NOT EXISTS `placeholders` VARCHAR(255) DEFAULT NULL;
ALTER TABLE `settings` ADD COLUMN IF NOT EXISTS `setting_key` VARCHAR(100) UNIQUE NOT NULL;
ALTER TABLE `settings` ADD COLUMN IF NOT EXISTS `setting_value` TEXT;
ALTER TABLE `settings` ADD COLUMN IF NOT EXISTS `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE `contacts` ADD COLUMN IF NOT EXISTS `user_id` INT NOT NULL;
ALTER TABLE `contacts` ADD COLUMN IF NOT EXISTS `first_name` VARCHAR(50) NOT NULL;
ALTER TABLE `contacts` ADD COLUMN IF NOT EXISTS `last_name` VARCHAR(50);
ALTER TABLE `contacts` ADD COLUMN IF NOT EXISTS `email` VARCHAR(255);
ALTER TABLE `contacts` ADD COLUMN IF NOT EXISTS `phone` VARCHAR(20);
ALTER TABLE `contacts` ADD COLUMN IF NOT EXISTS `company` VARCHAR(100);
ALTER TABLE `contacts` ADD COLUMN IF NOT EXISTS `status` VARCHAR(20) DEFAULT 'lead';
ALTER TABLE `contacts` ADD COLUMN IF NOT EXISTS `tags` TEXT;
ALTER TABLE `contacts` ADD COLUMN IF NOT EXISTS `notes` TEXT;
ALTER TABLE `contacts` ADD COLUMN IF NOT EXISTS `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `contacts` ADD COLUMN IF NOT EXISTS `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE `contacts` ADD COLUMN IF NOT EXISTS `points` VARCHAR(255) DEFAULT NULL;
ALTER TABLE `ai_tools` ADD COLUMN IF NOT EXISTS `user_id` INT NOT NULL;
ALTER TABLE `ai_tools` ADD COLUMN IF NOT EXISTS `tool_name` VARCHAR(100) NOT NULL;
ALTER TABLE `ai_tools` ADD COLUMN IF NOT EXISTS `category` VARCHAR(50);
ALTER TABLE `ai_tools` ADD COLUMN IF NOT EXISTS `description` TEXT;
ALTER TABLE `ai_tools` ADD COLUMN IF NOT EXISTS `url` VARCHAR(500);
ALTER TABLE `ai_tools` ADD COLUMN IF NOT EXISTS `daily_usage` INT DEFAULT 0;
ALTER TABLE `ai_tools` ADD COLUMN IF NOT EXISTS `weekly_usage` INT DEFAULT 0;
ALTER TABLE `ai_tools` ADD COLUMN IF NOT EXISTS `monthly_usage` INT DEFAULT 0;
ALTER TABLE `ai_tools` ADD COLUMN IF NOT EXISTS `rating` INT DEFAULT 0;
ALTER TABLE `ai_tools` ADD COLUMN IF NOT EXISTS `notes` TEXT;
ALTER TABLE `ai_tools` ADD COLUMN IF NOT EXISTS `is_favorite` BOOLEAN DEFAULT FALSE;
ALTER TABLE `ai_tools` ADD COLUMN IF NOT EXISTS `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `ai_tools` ADD COLUMN IF NOT EXISTS `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE `ai_tools` ADD COLUMN IF NOT EXISTS `points` VARCHAR(255) DEFAULT NULL;
ALTER TABLE `productivity_sessions` ADD COLUMN IF NOT EXISTS `user_id` INT NOT NULL;
ALTER TABLE `productivity_sessions` ADD COLUMN IF NOT EXISTS `session_name` VARCHAR(100) NOT NULL;
ALTER TABLE `productivity_sessions` ADD COLUMN IF NOT EXISTS `ai_tools_used` TEXT;
ALTER TABLE `productivity_sessions` ADD COLUMN IF NOT EXISTS `duration_minutes` INT DEFAULT 0;
ALTER TABLE `productivity_sessions` ADD COLUMN IF NOT EXISTS `productivity_score` INT DEFAULT 0;
ALTER TABLE `productivity_sessions` ADD COLUMN IF NOT EXISTS `notes` TEXT;
ALTER TABLE `productivity_sessions` ADD COLUMN IF NOT EXISTS `session_date` DATE;
ALTER TABLE `productivity_sessions` ADD COLUMN IF NOT EXISTS `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `productivity_sessions` ADD COLUMN IF NOT EXISTS `points` VARCHAR(255) DEFAULT NULL;
ALTER TABLE `achievements` ADD COLUMN IF NOT EXISTS `user_id` INT NOT NULL;
ALTER TABLE `achievements` ADD COLUMN IF NOT EXISTS `achievement_type` VARCHAR(50) NOT NULL;
ALTER TABLE `achievements` ADD COLUMN IF NOT EXISTS `achievement_name` VARCHAR(100) NOT NULL;
ALTER TABLE `achievements` ADD COLUMN IF NOT EXISTS `description` TEXT;
ALTER TABLE `achievements` ADD COLUMN IF NOT EXISTS `points` INT DEFAULT 0;
ALTER TABLE `achievements` ADD COLUMN IF NOT EXISTS `unlocked_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
